name: CI

on: [push]

jobs:
  test:
    name: Test on destination ${{ matrix.destination }}
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["platform=macOS"]
    
    steps:
    - uses: actions/checkout@v1
    - name: xcodebuild for ${{ matrix.destination }}
      run: set -o pipefail && xcodebuild test -scheme OperationPlus -destination "${{ matrix.destination }}" | xcpretty
    - name: SPM
      run: swift test
