name: CI

on: [push]

jobs:
  test:
    name: Test on destination ${{ matrix.destination }}
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["platform=macOS"]
    
    steps:
    - uses: actions/checkout@v1
    - name: test ${{ matrix.destination }}
      run: swift test
